### ISSUE TITLE
Internet connection probably new bug

### ISSUE THREAD

**Issue by CrimsonReza** [GoodDay360/Tempest-Launcher#4]
![image](https://user-images.githubusercontent.com/91114229/147576576-a3ab27c1-9f9e-49fe-82bd-986f21ecd964.png)

**Comment by GoodDay360** [comment]
Get the new update applied in 1.8.5. or download and install it again. I just moved the database this morning.

**Comment by GoodDay360** [comment]
13h ago. damn it in middle of the night.
